import path from 'node:path';
import { migrate } from 'drizzle-orm/node-postgres/migrator';
import { db, pool } from './client.js';
import { assertMigrationsSafe, LegacyDataBlockedError, REPAIR_INSTRUCTIONS } from '../modules/migration/migrationGate.js';

// server/db/migrations never moves (lives outside src/, generated by
// drizzle-kit) — compiled, this file becomes server/dist/db/migrate.js,
// hence the two '..' up from dist/db to server/, then into db/migrations.
const MIGRATIONS_FOLDER = path.join(import.meta.dirname, '..', '..', 'db', 'migrations');

/** Applies pending migrations. Used both at server boot (src/index.ts) and
 * by `npm run db:migrate` — the runner lives in drizzle-orm (not
 * drizzle-kit, a devDependency), so the production image (no
 * devDependencies) can still migrate. */
export async function runMigrations(): Promise<void> {
  // refuses (before touching anything) when legacy data would make a pending
  // migration fail half-way — see modules/migration/migrationGate.ts
  await assertMigrationsSafe(pool);
  await migrate(db, { migrationsFolder: MIGRATIONS_FOLDER });
}

/** Human-readable explanation for a blocked migration, or null for any other error. */
export function describeBlockedMigration(err: unknown): string | null {
  if (!(err instanceof LegacyDataBlockedError)) return null;
  return `${err.message}\n\n${err.report}\n\n${REPAIR_INSTRUCTIONS}`;
}

export { MIGRATIONS_FOLDER };

// run directly from the command line: applies and exits the process.
if (process.argv[1] === import.meta.filename) {
  runMigrations()
    .then(() => { console.log('Migrations applied.'); return pool.end(); })
    .then(() => process.exit(0))
    .catch((err) => {
      console.error('Failed to apply migrations:', describeBlockedMigration(err) ?? (err instanceof Error ? err.stack : err));
      process.exit(1);
    });
}
